"""Project marketing bot - generates legitimate growth suggestions.

This bot generates suggestions for improving project visibility, but does NOT:
- Auto-star repositories
- Create fake engagement
- Post to external platforms automatically

It only generates DRAFTS for human review.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .. import logger
from ..policy import Policy


@dataclass
class MarketingSuggestion:
    """A marketing suggestion draft."""
    category: str  # "readme", "docs", "showcase", "release_notes"
    title: str
    content: str
    priority: str = "medium"  # "high", "medium", "low"
    effort: str = "medium"   # "high", "medium", "low"


def generate_readme_suggestions(policy: Policy) -> list[MarketingSuggestion]:
    """Generate README optimization suggestions."""
    suggestions = []

    # Check if README has these sections
    readme_path = Path("README.md")
    if not readme_path.exists():
        readme_path = Path("README_CONTRIB_CENTER.md")

    if readme_path.exists():
        content = readme_path.read_text(encoding="utf-8")

        # Check for demo section
        if "## Demo" not in content and "## 示例" not in content:
            suggestions.append(MarketingSuggestion(
                category="readme",
                title="Add Demo section to README",
                content="Add a demo GIF or screenshot section to show the tool in action.",
                priority="high",
                effort="low",
            ))

        # Check for badges
        if "badge" not in content.lower():
            suggestions.append(MarketingSuggestion(
                category="readme",
                title="Add status badges",
                content="Add build status, PyPI version, license badges.",
                priority="medium",
                effort="low",
            ))

        # Check for TOC
        if "## Table of Contents" not in content and "[TOC]" not in content:
            suggestions.append(MarketingSuggestion(
                category="readme",
                title="Add Table of Contents",
                content="Add a TOC to help users navigate the README.",
                priority="medium",
                effort="low",
            ))

    return suggestions


def generate_docs_suggestions(policy: Policy) -> list[MarketingSuggestion]:
    """Generate documentation improvement suggestions."""
    suggestions = []

    # Check if docs directory exists
    docs_path = Path("docs")
    if not docs_path.exists():
        suggestions.append(MarketingSuggestion(
            category="docs",
            title="Create documentation directory",
            content="Create a `docs/` directory with user guides and API reference.",
            priority="high",
            effort="medium",
        ))

    return suggestions


def generate_showcase_suggestions(policy: Policy) -> list[MarketingSuggestion]:
    """Generate showcase content suggestions."""
    suggestions = []

    # Suggest creating a showcase of successful contributions
    suggestions.append(MarketingSuggestion(
        category="showcase",
        title="Create contribution showcase",
        content="Create a markdown file showcasing successful PRs generated by the tool.",
        priority="medium",
        effort="medium",
    ))

    return suggestions


def generate_release_notes_suggestions(policy: Policy) -> list[MarketingSuggestion]:
    """Generate release notes suggestions."""
    suggestions = []

    # Check if there's a CHANGELOG
    changelog = Path("CHANGELOG.md")
    if not changelog.exists():
        suggestions.append(MarketingSuggestion(
            category="release_notes",
            title="Create CHANGELOG.md",
            content="Create a changelog to track version history.",
            priority="high",
            effort="low",
        ))

    return suggestions


def generate_all_suggestions(policy: Policy) -> list[MarketingSuggestion]:
    """Generate all marketing suggestions."""
    suggestions = []
    suggestions.extend(generate_readme_suggestions(policy))
    suggestions.extend(generate_docs_suggestions(policy))
    suggestions.extend(generate_showcase_suggestions(policy))
    suggestions.extend(generate_release_notes_suggestions(policy))
    return suggestions


def save_suggestions(suggestions: list[MarketingSuggestion], output_path: Path) -> None:
    """Save suggestions to a markdown file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Project Marketing Suggestions",
        "",
        "**These are DRAFTS for human review. Nothing is auto-published.**",
        "",
    ]

    # Group by category
    by_category: dict[str, list[MarketingSuggestion]] = {}
    for s in suggestions:
        by_category.setdefault(s.category, []).append(s)

    for category, items in by_category.items():
        lines.append(f"## {category}")
        lines.append("")
        for i, s in enumerate(items, 1):
            lines.append(f"### {i}. {s.title}")
            lines.append("")
            lines.append(f"**Priority**: {s.priority}")
            lines.append(f"**Effort**: {s.effort}")
            lines.append("")
            lines.append(s.content)
            lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    logger.log_action(
        "marketing_suggestions_generated",
        count=len(suggestions),
        output=str(output_path),
    )
