"""Autopilot Publisher - Automatic External PR Publishing

Implements automatic external PR publishing using the fork mode workflow.

This module is only used when mode=autopilot. It:
  1. Reads patch metadata generated by mini_swe_adapter
  2. Filters safe candidates
  3. Selects the best candidate (highest score, safest)
  4. Calls external_pr_publisher to publish
  5. Records the result in data/published_prs.jsonl

Safety guarantees:
  - Max 1 PR per day
  - Max 1 PR per run
  - Only low-risk issues (docs, tests, typos)
  - No security/auth/payment/credential issues
  - No private/internal repos
  - No automatic issue/comment/star
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

from . import logger
from .external_pr_publisher import PublishResult, publish_external_pr, dry_run_external_pr
from .policy import Policy, _load
from .visibility_guard import PermissionError_, guard_external_public_repo_read


# ---------------------------------------------------------------------------
# Config loader
# ---------------------------------------------------------------------------


def _load_autopilot_config() -> dict[str, Any]:
    """Load autopilot.yml configuration."""
    return _load("autopilot.yml")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_patch_metadata(today: str) -> list[dict]:
    """Load patch metadata from data/patches/YYYY-MM-DD/."""
    patches_dir = Path("data/patches") / today
    if not patches_dir.exists():
        return []

    metadata_list = []
    for json_file in patches_dir.glob("*.json"):
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                metadata = json.load(f)
                metadata["patch_file"] = str(json_file.with_suffix(".diff"))
                metadata_list.append(metadata)
        except Exception as e:
            logger.log_action("patch_metadata_load_failed", file=str(json_file), error=str(e))
            continue

    return metadata_list


def _load_published_prs() -> list[dict]:
    """Load published PRs from data/published_prs.jsonl."""
    published_path = Path("data/published_prs.jsonl")
    if not published_path.exists():
        return []

    published = []
    with open(published_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                published.append(json.loads(line))
            except Exception:
                continue

    return published


def _can_publish_today(published: list[dict], config: dict) -> bool:
    """Check if we can publish today (rate limit).
    
    Only counts successful PR publications (ok=True and has pr_url).
    Failed attempts do not consume the daily quota.
    """
    max_per_day = config.get("max_external_prs_per_day", 1)
    today = datetime.now().strftime("%Y-%m-%d")

    today_count = sum(
        1
        for pr in published
        if pr.get("date", "").startswith(today)
        and pr.get("ok") is True
        and pr.get("pr_url")
    )
    return today_count < max_per_day


def _check_cooldown(repo: str, published: list[dict], config: dict) -> bool:
    """Check cooldown rules (same repo/owner).
    
    Only counts successful PR publications (ok=True and has pr_url).
    Failed attempts do not trigger cooldown.
    """
    cooldown = config.get("cooldown", {})
    repo_hours = cooldown.get("same_upstream_repo_hours", 72)
    owner_hours = cooldown.get("same_owner_hours", 24)

    now = datetime.now()
    owner = repo.split("/")[0] if "/" in repo else ""

    for pr in published:
        # Only consider successful PR publications for cooldown
        if pr.get("ok") is not True or not pr.get("pr_url"):
            continue
            
        pr_date_str = pr.get("date", "")
        if not pr_date_str:
            continue

        try:
            pr_date = datetime.fromisoformat(pr_date_str)
        except Exception:
            continue

        # Check same repo cooldown
        if pr.get("repo") == repo:
            if (now - pr_date).total_seconds() < repo_hours * 3600:
                return False

        # Check same owner cooldown
        if owner and "/" in pr.get("repo", ""):
            pr_owner = pr["repo"].split("/")[0]
            if pr_owner == owner:
                if (now - pr_date).total_seconds() < owner_hours * 3600:
                    return False

    return True


def _issue_already_published(issue_url: str, published: list[dict]) -> bool:
    """Check if an issue already has a successful PR published.
    
    Only counts successful PR publications (ok=True and has pr_url).
    Failed attempts do not block future attempts.
    """
    for pr in published:
        if pr.get("ok") is True and pr.get("pr_url") and pr.get("issue_url") == issue_url:
            return True
    return False


def _is_safe_candidate(metadata: dict, config: dict, policy: Policy) -> tuple[bool, str]:
    """Check if a candidate is safe to publish.
    
    Returns (is_safe, reject_reason).
    """
    # Check deny keywords in issue URL or repo
    issue_url = metadata.get("issue_url", "")
    repo = metadata.get("repo", "")

    try:
        guard_external_public_repo_read(repo, "read", policy)
    except PermissionError_:
        return False, "upstream_not_public"

    # Check score
    min_score = config.get("min_score", 7.0)
    if metadata.get("score", 0) < min_score:
        return False, "score_too_low"

    # Check patch_generated
    if config.get("require_patch_generated", True):
        if metadata.get("patch_generated") is not True:
            return False, "patch_not_generated"

    # Check patch file exists and is valid
    patch_file = metadata.get("patch_file", "")
    if not patch_file:
        return False, "patch_file_missing"

    patch_path = Path(patch_file)
    if not patch_path.exists():
        return False, "patch_file_missing"

    if not patch_path.is_file():
        return False, "patch_file_not_file"

    if patch_path.suffix != ".diff":
        return False, "patch_file_not_diff"

    # Check if patch file is empty
    try:
        patch_content = patch_path.read_text(encoding="utf-8").strip()
    except Exception:
        return False, "patch_file_read_error"
    
    if not patch_content:
        return False, "empty_patch"

    # Check diff limits
    if config.get("require_diff_limits", True):
        changed_files = metadata.get("changed_files", [])
        diff_lines = metadata.get("diff_lines", 0)

        max_files = config.get("safety", {}).get("max_changed_files", 5)
        max_lines = config.get("safety", {}).get("max_diff_lines", 200)

        if len(changed_files) > max_files:
            return False, "too_many_files"
        if diff_lines > max_lines:
            return False, "diff_too_large"

    # Check tests
    if config.get("require_tests_pass_or_not_available", True):
        tests_passed = metadata.get("tests_passed")
        if tests_passed is not None and not tests_passed:
            return False, "tests_failed"

    return True, ""


# ---------------------------------------------------------------------------
# Core autopilot publish function
# ---------------------------------------------------------------------------


def autopilot_publish_one(
    policy: Policy | None = None,
    dry_run: bool = False,
) -> dict:
    """Attempt to publish one external PR using autopilot mode.

    Args:
        policy: Policy object. If None, loads from policy.yml.
        dry_run: If True, run full validation but do not publish.

    Returns dict with:
      - ok: bool
      - published: bool
      - dry_run: bool (True if dry_run)
      - reason: str (if not published)
      - repo: str (if candidate selected)
      - issue_url: str (if candidate selected)
      - pr_url: str (if published)
      - error: str (if failed)
      - fork_repo: str (if dry_run and candidate selected)
      - branch: str (if dry_run and candidate selected)
      - patch_file: str (if candidate selected)
      - skipped_reason: str (if failed)
      - patch_stats: dict (if dry_run and candidate selected)
    """
    if policy is None:
        policy = Policy.load()

    # Check if autopilot is enabled
    config = _load_autopilot_config()
    if not config.get("enabled", False):
        return {
            "ok": True,
            "published": False,
            "reason": "autopilot_disabled",
        }

    # Check rate limit
    published = _load_published_prs()
    if not _can_publish_today(published, config):
        return {
            "ok": True,
            "published": False,
            "reason": "rate_limit_reached",
        }

    # Load today's patch metadata
    today = datetime.now().strftime("%Y-%m-%d")
    metadata_list = _load_patch_metadata(today)

    if not metadata_list:
        return {
            "ok": True,
            "published": False,
            "reason": "no_patch_generated",
        }

    # Sort by score (highest first)
    metadata_list.sort(key=lambda x: x.get("score", 0), reverse=True)

    # Find the first safe candidate
    selected = None
    reject_reason = "no_safe_candidate"

    for metadata in metadata_list:
        # Check if issue already published
        issue_url = metadata.get("issue_url", "")
        if _issue_already_published(issue_url, published):
            reject_reason = "issue_already_published"
            continue
            
        is_safe, reason = _is_safe_candidate(metadata, config, policy)
        if is_safe:
            # Check cooldown
            repo = metadata.get("repo", "")
            if _check_cooldown(repo, published, config):
                selected = metadata
                break
            else:
                reject_reason = "cooldown_active"
        else:
            reject_reason = reason

    if selected is None:
        return {
            "ok": True,
            "published": False,
            "reason": reject_reason,
        }

    # Publish the selected candidate
    issue_url = selected.get("issue_url", "")
    repo = selected.get("repo", "")
    patch_file = Path(selected.get("patch_file", ""))
    pr_title = selected.get("pr_title", f"Fix issue for {repo}")
    pr_body = selected.get("pr_body", f"Address issue: {issue_url}")

    # Build PR body using template
    template = config.get("pr_body_template", "")
    if template:
        tests_summary = "tests passed" if selected.get("tests_passed") else "tests not available"
        pr_body = template.format(
            summary=f"Address issue: {issue_url}",
            issue_url=issue_url,
            tests_summary=tests_summary,
        )

    # Branch: dry_run vs real publish
    if dry_run:
        # Dry-run: call dry_run_external_pr, do NOT publish

        result = dry_run_external_pr(
            issue_url=issue_url,
            upstream_repo=repo,
            patch_file=patch_file,
            pr_title=pr_title,
            policy=policy,
        )

        return {
            "ok": result.ok,
            "published": False,
            "dry_run": True,
            "repo": repo,
            "issue_url": issue_url,
            "patch_file": str(patch_file),
            "fork_repo": result.fork_repo,
            "branch": result.branch,
            "pr_url": None,
            "error": result.error,
            "skipped_reason": result.skipped_reason,
            "patch_stats": result.patch_stats,
            "selected": True,
        }

    # Real publish: call publish_external_pr
    result = publish_external_pr(
        issue_url=issue_url,
        upstream_repo=repo,
        patch_file=patch_file,
        pr_title=pr_title,
        pr_body=pr_body,
        policy=policy,
        confirm_publish=True,
    )

    # Record result
    record = {
        "date": datetime.now().isoformat(),
        "repo": repo,
        "issue_url": issue_url,
        "pr_url": result.pr_url,
        "branch": result.branch,
        "patch_file": str(patch_file),
        "mode": "autopilot",
        "ok": result.ok,
        "error": result.error,
        "skipped_reason": result.skipped_reason,
    }

    # Write to data/published_prs.jsonl
    published_path = Path("data/published_prs.jsonl")
    published_path.parent.mkdir(parents=True, exist_ok=True)
    with open(published_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

    # Write to reports/YYYY-MM-DD.md
    report_path = Path(f"reports/{today}.md")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    with open(report_path, "a", encoding="utf-8") as f:
        f.write(f"\n## Autopilot Publish Attempt\n\n")
        f.write(f"- **Repo**: {repo}\n")
        f.write(f"- **Issue**: {issue_url}\n")
        f.write(f"- **Result**: {'SUCCESS' if result.ok else 'FAILED'}\n")
        if result.ok:
            f.write(f"- **PR**: {result.pr_url}\n")
        else:
            f.write(f"- **Error**: {result.error}\n")
            f.write(f"- **Reason**: {result.skipped_reason}\n")

    logger.log_action(
        "autopilot_publish_attempt",
        repo=repo,
        issue=issue_url,
        ok=result.ok,
        pr_url=result.pr_url,
    )

    if result.ok:
        return {
            "ok": True,
            "published": True,
            "repo": repo,
            "issue_url": issue_url,
            "patch_file": str(patch_file),
            "fork_repo": result.fork_repo,
            "branch": result.branch,
            "pr_url": result.pr_url,
        }
    else:
        return {
            "ok": False,
            "published": False,
            "repo": repo,
            "issue_url": issue_url,
            "error": result.error,
            "skipped_reason": result.skipped_reason,
        }


